import { IgcBadgeComponent } from './src/components/badge/badge.js';
import { IgcAvatarComponent } from './src/components/avatar/avatar.js';
import { IgcButtonComponent } from './src/components/button/button.js';
import { IgcFormComponent } from './src/components/form/form.js';
import { IgcCardComponent } from './src/components/card/card.js';
import { IgcCardActions } from './src/components/card/card.actions.js';
import { IgcCardContent } from './src/components/card/card.content.js';
import { IgcCardHeader } from './src/components/card/card.header.js';
import { IgcCardMedia } from './src/components/card/card.media.js';
import { IgcCheckboxComponent } from './src/components/checkbox/checkbox.js';
import { IgcLinkButtonComponent } from './src/components/button/link-button.js';
import { IgcListHeaderComponent } from './src/components/list/list-header.js';
import { IgcListItemComponent } from './src/components/list/list-item.js';
import { IgcListComponent } from './src/components/list/list.js';
import { IgcSwitchComponent } from './src/components/checkbox/switch.js';
import { IgcNavbarComponent } from './src/components/navbar/navbar.js';
import { IgcIconComponent } from './src/components/icon/icon.js';
import { IgcIconButtonComponent } from './src/components/button/icon-button.js';
import { IgcInputComponent } from './src/components/input/input.js';
import { IgcRadioComponent } from './src/components/radio/radio.js';
import { IgcRadioGroupComponent } from './src/components/radio-group/radio-group.js';
import { IgniteuiWebcomponents } from './src/IgniteuiWebcomponents.js';
import { IgcDaysViewComponent } from './src/components/calendar/days-view/days-view.js';
import { IgcMonthsViewComponent } from './src/components/calendar/months-view/months-view.js';
import { IgcYearsViewComponent } from './src/components/calendar/years-view/years-view.js';
import { IgcCalendarComponent } from './src/components/calendar/calendar.js';
import { IgcRippleComponent } from './src/components/ripple/ripple.js';
import { IgcNavDrawerItemComponent } from './src/components/nav-drawer/nav-drawer-item.js';
import { IgcNavDrawerComponent } from './src/components/nav-drawer/nav-drawer.js';
import { IgcNavDrawerHeaderItemComponent } from './src/components/nav-drawer/nav-drawer-header-item.js';

window.customElements.define('igniteui-webcomponents', IgniteuiWebcomponents);
window.customElements.define('igc-avatar', IgcAvatarComponent);
window.customElements.define('igc-badge', IgcBadgeComponent);
window.customElements.define('igc-button', IgcButtonComponent);
window.customElements.define('igc-form', IgcFormComponent);
window.customElements.define('igc-card', IgcCardComponent);
window.customElements.define('igc-card-header', IgcCardHeader);
window.customElements.define('igc-card-media', IgcCardMedia);
window.customElements.define('igc-card-content', IgcCardContent);
window.customElements.define('igc-card-actions', IgcCardActions);
window.customElements.define('igc-checkbox', IgcCheckboxComponent);
window.customElements.define('igc-link-button', IgcLinkButtonComponent);
window.customElements.define('igc-list', IgcListComponent);
window.customElements.define('igc-list-header', IgcListHeaderComponent);
window.customElements.define('igc-list-item', IgcListItemComponent);
window.customElements.define('igc-switch', IgcSwitchComponent);
window.customElements.define('igc-navbar', IgcNavbarComponent);
window.customElements.define('igc-icon', IgcIconComponent);
window.customElements.define('igc-icon-button', IgcIconButtonComponent);
window.customElements.define('igc-input', IgcInputComponent);
window.customElements.define('igc-radio', IgcRadioComponent);
window.customElements.define('igc-radio-group', IgcRadioGroupComponent);
window.customElements.define('igc-days-view', IgcDaysViewComponent);
window.customElements.define('igc-months-view', IgcMonthsViewComponent);
window.customElements.define('igc-years-view', IgcYearsViewComponent);
window.customElements.define('igc-calendar', IgcCalendarComponent);
window.customElements.define('igc-ripple', IgcRippleComponent);

window.customElements.define('igc-nav-drawer', IgcNavDrawerComponent);
window.customElements.define('igc-nav-drawer-item', IgcNavDrawerItemComponent);
window.customElements.define(
  'igc-nav-drawer-header-item',
  IgcNavDrawerHeaderItemComponent
);
