import { consume } from '@lit/context';
import { html, LitElement, nothing, type PropertyValues } from 'lit';
import { property, state } from 'lit/decorators.js';
import { addThemingController } from '../../theming/theming-controller.js';
import IgcAvatarComponent from '../avatar/avatar.js';
import { chatContext } from '../common/context.js';
import { registerComponent } from '../common/definitions/register.js';
import type { ChatState } from './chat-state.js';
import IgcMessageAttachmentsComponent from './message-attachments.js';
import { styles } from './themes/message.base.css.js';
import { all } from './themes/message.js';
import { styles as shared } from './themes/shared/chat-message/chat-message.common.css.js';
import type { ChatMessageRenderer, IgcMessage } from './types.js';

/**
 * A chat message component for displaying individual messages in `<igc-chat>`.
 *
 * @element igc-chat-message
 *
 * This component renders a single chat message including:
 * - Message text (sanitized)
 * - Attachments (if any)
 * - Custom templates for message content and actions (if provided via chat options)
 *
 * It distinguishes sent messages from received messages by comparing
 * the message sender with the current user ID from chat state.
 *
 * The message text can be rendered with a markdown renderer if provided.
 */
export default class IgcChatMessageComponent extends LitElement {
  /** Tag name of the custom element. */
  public static readonly tagName = 'igc-chat-message';

  /** Styles applied to the component. */
  public static override styles = [styles, shared];

  /**
   * Registers this component and its dependencies.
   * This is used internally to set up the component definitions.
   */
  /* blazorSuppress */
  public static register() {
    registerComponent(
      IgcChatMessageComponent,
      IgcMessageAttachmentsComponent,
      IgcAvatarComponent
    );
  }

  /**
   * Injected chat state context. Provides message data, user info, and options.
   * @private
   */
  @consume({ context: chatContext, subscribe: true })
  private _chatState?: ChatState;

  /**
   * The chat message to render.
   */
  @property({ attribute: false })
  public message: IgcMessage | undefined;

  /**
   * The rendered HTML content generated by the message renderer.
   * This is updated when the message or renderer changes.
   */
  @state()
  private renderedContent: unknown = html``;

  /**
   * The renderer instance responsible for converting message data into HTML.
   * Typically provided through component options or chat state.
   */
  @state()
  private renderer?: ChatMessageRenderer;

  /**
   * Renders the current message using the assigned `renderer`.
   * If no message is available or renderer is missing, sets empty HTML.
   *
   * @returns {Promise<void>} A promise that resolves once rendering is complete.
   */
  private async renderContent(): Promise<void> {
    if (!this.message) return;
    const rendered = (await this.renderer?.render(this.message)) ?? html``;
    this.renderedContent = rendered;
  }

  /**
   * Lit lifecycle method called after the component's first update.
   * Initializes the `renderer` from chat state options if available.
   *
   * @param _changedProperties - The properties that changed before the update.
   */
  protected override async firstUpdated(
    _changedProperties: PropertyValues
  ): Promise<void> {
    super.updated(_changedProperties);
    this.renderer = this._chatState?.options?.messageRenderer;
  }

  /**
   * Lit lifecycle method called after any update to the component.
   * Triggers re-rendering when `message` or `renderer` has changed.
   *
   * @param changedProps - A map of changed properties and their previous values.
   */
  protected override async updated(
    changedProps: Map<string, any>
  ): Promise<void> {
    if (changedProps.has('message') || changedProps.has('renderer')) {
      await this.renderContent();
    }
  }

  constructor() {
    super();
    addThemingController(this, all);
  }

  /**
   * Renders the chat message template.
   * - Applies 'sent' CSS class if the message sender matches current user.
   * - Uses markdown rendering if configured.
   * - Renders attachments and custom templates if provided.
   */
  protected override render() {
    const containerPart = `message-container ${this.message?.sender === this._chatState?.currentUserId ? 'sent' : ''}`;

    return html`
      <div part=${containerPart}>
        <div part="bubble">
          ${this._chatState?.options?.templates?.messageTemplate && this.message
            ? this._chatState.options.templates.messageTemplate(this.message)
            : html`${this.renderedContent}
              ${this.message?.attachments &&
              this.message?.attachments.length > 0
                ? html`<igc-message-attachments
                    .attachments=${this.message?.attachments}
                  >
                  </igc-message-attachments>`
                : nothing}`}
          ${this.message?.attachments && this.message?.attachments.length > 0
            ? html`<igc-message-attachments .message=${this.message}>
              </igc-message-attachments>`
            : nothing}
          ${this._chatState?.options?.templates?.messageActionsTemplate &&
          this.message
            ? this._chatState.options.templates.messageActionsTemplate(
                this.message
              )
            : nothing}
        </div>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'igc-chat-message': IgcChatMessageComponent;
  }
}
