/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IgcButton {
        "background": string;
        "buttonType": 'button' | 'reset' | 'submit';
        "color": string;
        "disabled": boolean;
        "download": string;
        "href": string;
        "rel": string;
        "size": 'small' | 'medium' | 'large';
        "target": '_blank' | '_parent' | '_self' | '_top';
        "type": 'flat' | 'raised' | 'outlined' | 'icon' | 'fab';
    }
}
declare global {
    interface HTMLIgcButtonElement extends Components.IgcButton, HTMLStencilElement {
    }
    var HTMLIgcButtonElement: {
        prototype: HTMLIgcButtonElement;
        new (): HTMLIgcButtonElement;
    };
    interface HTMLElementTagNameMap {
        "igc-button": HTMLIgcButtonElement;
    }
}
declare namespace LocalJSX {
    interface IgcButton {
        "background"?: string;
        "buttonType"?: 'button' | 'reset' | 'submit';
        "color"?: string;
        "disabled"?: boolean;
        "download"?: string;
        "href"?: string;
        "rel"?: string;
        "size"?: 'small' | 'medium' | 'large';
        "target"?: '_blank' | '_parent' | '_self' | '_top';
        "type"?: 'flat' | 'raised' | 'outlined' | 'icon' | 'fab';
    }
    interface IntrinsicElements {
        "igc-button": IgcButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "igc-button": LocalJSX.IgcButton & JSXBase.HTMLAttributes<HTMLIgcButtonElement>;
        }
    }
}
